language: ruby
sudo: required
cache: bundler
bundler_args: --without development
before_install:
  - gem update --system
  - gem --version
stages:
  - name: e2e
    if: type IN (pull_request, cron)
  - name: publish binary
    if: tag IS present
jobs:
  include:
    - stage: e2e
      name: "e2e: xenial docker with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: xenial
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=weave
    - stage: e2e
      name: "e2e: xenial docker with calico"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: xenial
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=calico
    - stage: e2e
      name: "e2e: bionic docker with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=weave
    - stage: e2e
      name: "e2e: bionic bdocker with calico"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=calico
    - stage: publish binary
      script: ./build/travis/macos.sh
      os: osx
      install: ls -l
      env:
        - secure: "FLhmFZTMyXwngw9dZgi5X2I+6z5RwjMO0x+MeqG1ujniFEloONUsJHxSu7al9KPQECp9fZC4+GewaR088PXd00bCGYVvSiIn+S+ZbNqkOtv0QFPllvZooTZtMS+inqocr6pv4BJfALytcZQuaKrJ6iVdN7bu62n3/IBDfyvtBZYnWakeVe2k1mW1XUld/YuCjHe7wRFfAMOYu4+9LAhFyJgrpPRkhPMXkuvYaxGoeqcamc5AbMrRnDapTkLJBUc1TlmSY0wMEAhX4+yL8zehihEU6wGq05BGNfigJIpQkuj62zmQZdZkE3y9x4DGZauPDXNPhyYWqdxRm3KExHhJwLrY6d4L8l6snYAG7STPIziqNfotPzcTvM5/hhUkD65JpxO7rNq7BcYjV2fYfN8IgAHR/+wgDo7p4v+Y7fh6QsJ1oOujTsvIZDRE/Ly/Q2CKsdY2HqJfoROWh8/NWBEGcx+aRQekj9h7jbLqpML2LNa8Y9FOx86GFOskEi8tPmZ+drokxhakd+P6pdfdzwjHr1RwOH9z115tkG0HDKk6WnjTosGctBrUSzQGozv5HHEU3hRdnLLgyLZKdr+GRa6jHCnP/8qq3DjXey7RGOXI/b1okhgnAOJK38do65UIaJncijmWOl0w0pfrRuk/KA5QhwUWJTf/VGnnGgYg/dF9xhY=" # GITHUB_TOKEN

